---
title: "MECC Hydraulic Analysis"
output: html_document
---

NOTE: This is currently using sample cross section data from another project

```{r message=FALSE, warning=FALSE}
library(tidyverse)
ggplot2::theme_set(theme_classic())
```

# Import cross sections

```{r message=FALSE, warning=FALSE}
prep_xs <- function(data, sta, elev, delta_x=0.1) {
  result <- data %>%
    arrange({{sta}}) %>%
    mutate(sta = {{sta}}) %>%
    complete(sta = seq(from = min({{sta}}), to = max({{sta}}), by = delta_x)) %>%
    mutate(gse = zoo::na.approx({{elev}}, x = sta)) %>% 
    select(c(sta, gse))
  
  # further densify in the vertical direction
  d <- result %>% 
      arrange(-sta) %>%
      mutate(delta_x = abs(lag(sta, 1) - sta),
             delta_z = abs(lag(gse, 1) - gse),
             multiplier = replace_na(ceiling(delta_z/delta_x),1)) %>% 
      arrange(sta)
  idx <- rep(1:nrow(d), d$multiplier)
  return(
    d[idx,] %>% 
    mutate(gse = case_when(duplicated(sta) ~ NA, TRUE ~ gse),
           sta = case_when(duplicated(sta) ~ NA, TRUE ~ sta)) %>%
    mutate(gse = zoo::na.approx(gse, na.rm = FALSE),
           sta = zoo::na.approx(sta, na.rm = FALSE)) %>%
    select(sta, gse) %>% drop_na() 
  )
  
}

```

```{r message=FALSE, warning=FALSE}
xs_2007 <- read_csv("data/xs_2007.csv") %>%
  prep_xs(sta = station_ft, elev = elevation_ft) 

xs_2007 %>% ggplot(aes(y = gse, x = sta)) + geom_point() + 
  ylab("Elevation (ft)") + xlab("Station (ft)") + ggtitle("2007 Baseline")
```

```{r message=FALSE, warning=FALSE}
xs_2023 <- read_csv("data/xs_2023_simplified.csv") %>%
  prep_xs(sta = station_ft, elev = elevation_ft) 

xs_2023 %>% ggplot(aes(y = gse, x = sta)) + geom_point() + 
  ylab("Elevation (ft)") + xlab("Station (ft)") + ggtitle("2023 Proposed")
```




```{r message=FALSE, warning=FALSE}
ggplot() + 
  geom_line(data = xs_2007, aes(x = sta, y = gse, color = "2007 Baseline")) +
  geom_line(data = xs_2023, aes(x = sta, y = gse, color = "2023 Proposed")) +
  ylab("Elevation (ft)") + xlab("Station (ft)") + theme(legend.position="top", legend.title=element_blank())
```

# Calculate depth-discharge rating curves 

```{r message=FALSE, warning=FALSE}

model_slope <- (38.6-38.0) / 28.65

model_roughness <- 0.035 # n

print(c("model_slope" = model_slope, "model_roughness" = model_roughness))
```


```{r message=FALSE, warning=FALSE}
calc_xs <- function(data, water_elev) {
  data %>% 
    arrange(sta) %>%
    mutate(wse = case_when(water_elev > gse ~ water_elev),
           delta_x = abs(lag(sta, 1) - sta),
           delta_z = abs(lag(gse, 1) - gse),
           depth = wse - gse, 
           hyp_length = sqrt(delta_x^2 + delta_z^2)
    ) %>%
    filter(!is.na(wse)) %>% 
    summarize(thalweg_elevation = min(gse),
              water_surface_elevation = water_elev,
              max_depth = water_surface_elevation - thalweg_elevation,
              cross_sectional_area = sum(delta_x * depth),
              wetted_perimeter = sum(hyp_length),
    ) %>% 
    as.list() %>% 
    list_flatten()
}

calculate_rating_curve <- function(data, slope, mannings_n, delta_y=0.1) {
  depth_vs_wse <- seq(from=min(data$gse)+delta_y, to=max(data$gse), by=delta_y) %>% 
    as_tibble() %>%
    mutate(result = map(value, function(x){calc_xs(data = data, water_elev = x)})) %>% 
    unnest_wider(col = result) %>%
    drop_na() %>%
    mutate(discharge_cfs = 1.486 * cross_sectional_area * 
             (cross_sectional_area / wetted_perimeter)^(2/3) * slope^(1/2) * mannings_n^(-1),
           velocity_ft_s = discharge_cfs / cross_sectional_area) %>%
    arrange(discharge_cfs)
}
```

```{r message=FALSE }
depth_vs_discharge_2007 <- xs_2007 %>% 
  calculate_rating_curve(slope = model_slope,
                         mannings_n = model_roughness)
depth_vs_discharge_2007 %>% 
  ggplot(aes(y = max_depth, x = discharge_cfs)) + 
  geom_line() + ylab("Depth (ft)") + xlab("Discharge (cfs)") + ggtitle("2007 Baseline")
```

```{r message=FALSE, warning=FALSE}
depth_vs_discharge_2023 <- xs_2023 %>% 
  calculate_rating_curve(slope = model_slope,
                         mannings_n = model_roughness)
depth_vs_discharge_2023 %>% 
  ggplot(aes(y = max_depth, x = discharge_cfs)) + 
  geom_line() + ylab("Depth (ft)") + xlab("Discharge (cfs)") + ggtitle("2023 Proposed") 
```

```{r message=FALSE, warning=FALSE}
ggplot() +
  geom_line(data = depth_vs_discharge_2007, aes(y = max_depth, x = discharge_cfs, color = "2007 Baseline")) +
  geom_line(data = depth_vs_discharge_2023, aes(y = max_depth, x = discharge_cfs, color = "2023 Proposed")) + 
  ylab("Depth (ft)") + xlab("Discharge (cfs)") + theme(legend.position="top", legend.title=element_blank())
```
```{r message=FALSE, warning=FALSE}
ggplot() +
  geom_line(data = depth_vs_discharge_2007, aes(y = water_surface_elevation, x = discharge_cfs, color = "2007 Baseline")) +
  geom_line(data = depth_vs_discharge_2023, aes(y = water_surface_elevation, x = discharge_cfs, color = "2023 Proposed")) + 
  ylab("Water Surface Elevation (ft)") + xlab("Discharge (cfs)") + theme(legend.position="top", legend.title=element_blank())
```

# Interpolate water surface for selected discharge

```{r message=FALSE, warning=FALSE}
model_discharge <- 3980 # cfs
```

```{r message=FALSE, warning=FALSE}
interpolate_rating_curve <- function(data, discharge) {
  data %>%
    bind_rows(tribble(~selected_water_level, ~discharge_cfs, TRUE, discharge)) %>%
    arrange(discharge_cfs) %>%
    mutate(output_wse = zoo::na.approx(water_surface_elevation)) %>%
    filter(selected_water_level) %>% 
    pull(output_wse)
}
```

```{r message=FALSE, warning=FALSE}
wse_2007 <- depth_vs_discharge_2007 %>% interpolate_rating_curve(model_discharge)
print(c("wse 2007" = wse_2007))
```

```{r message=FALSE, warning=FALSE}
wse_2023 <- depth_vs_discharge_2023 %>% interpolate_rating_curve(model_discharge)
print(c("wse 2023" = wse_2023))
```

```{r message=FALSE, warning=FALSE}
xs_2007 %>% calc_xs(wse_2007)
```

```{r message=FALSE, warning=FALSE}
xs_2023 %>% calc_xs(wse_2023)
```

# Plot outputs

```{r message=FALSE, warning=FALSE}
xs_2007 %>% arrange(sta) %>%
      mutate(wse = case_when(wse_2007 > gse ~ wse_2007)) %>%
      ggplot(aes(x = sta)) + 
      geom_line(aes(y = gse)) + 
      geom_line(aes(y = wse)) + 
      ylab("Station (ft)") + xlab("Elevation (ft)") + ggtitle("2007 Baseline")
```
```{r message=FALSE, warning=FALSE}
xs_2023 %>% arrange(sta) %>%
      mutate(wse = case_when(wse_2023 > gse ~ wse_2023)) %>%
      ggplot(aes(x = sta)) + 
      geom_line(aes(y = gse)) + 
      geom_line(aes(y = wse)) + 
      ylab("Station (ft)") + xlab("Elevation (ft)") + ggtitle("2023 Proposed")
```

```{r message=FALSE, warning=FALSE}
ggplot() + 
  geom_line(data = xs_2007, aes(x = sta, y = gse, color = "2007 Baseline", linetype = "Terrain")) +
  geom_line(data = xs_2023, aes(x = sta, y = gse, color = "2023 Proposed", linetype = "Terrain")) +
  geom_line(data = xs_2007, aes(x = sta, y = case_when(wse_2007 > gse ~ wse_2007), 
                                color = "2007 Baseline", linetype = "Water Surface")) + 
  geom_line(data = xs_2023, aes(x = sta, y = case_when(wse_2023 > gse ~ wse_2023), 
                                color = "2023 Proposed", linetype = "Water Surface")) + 
      ylab("Station (ft)") + xlab("Elevation (ft)") + theme(legend.position="top", legend.title=element_blank())
```

Calculate design velocity for 2023

```{r message=FALSE, warning=FALSE}

velocity_2007 <- model_discharge / calc_xs(xs_2007, wse_2007)$cross_sectional_area
print(velocity_2007)

```


```{r message=FALSE, warning=FALSE}

velocity_2023 <- model_discharge / calc_xs(xs_2023, wse_2023)$cross_sectional_area
print(velocity_2023)

```

